### PR TITLE
added pagination for episodes

### PR DESCRIPTION
**Pull request by Denrage**
Added missing pagination which result in missing episode names. This change will request all available pages from the episodes endpoint

### CODE REVIEW

**Comment by Nearata** [comment]
KeyError on line 189

**Comment by Denrage** [comment]
Hmmm, i didn't change anything near that line and also didn't change what gets written into the metadata so, idk why you would get a KeyError on that position (at least in my testing it didn't even happen)  .
Would need more information, so i can reproduce it and see what fails

**Comment by Nearata** [comment]
```sh
posters_data = get_json(JIKAN_URL + JIKAN_ANIME_EPISODES.format(id=sequel_id))

KeyError: 'page'
```

**Comment by Denrage** [comment]
Tested it now multiple times with Hunter x Hunter without any problems at all. Therefor w/o any information how you produce that error, i can't reproduce it and i think that it has nothing to do with the changes i made, bc i can't see any connection why my changes should provoke that error.

```
2021-02-18 04:06:19,397 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/1925/tree'
2021-02-18 04:06:24,075 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/search/anime?q=Hunter%20X%20Hunter&limit=10'
2021-02-18 04:06:27,234 (1550acd6b640) :  DEBUG (runtime:88) - Sending packed state data (109 bytes)
2021-02-18 04:06:27,235 (1550acd6b640) :  DEBUG (runtime:924) - Response: [200] str, 3776 bytes
2021-02-18 04:06:27,298 (1550acd6b640) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.github.nearata.jikanplex/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNAoxOTI1czQKZGJpZGkwCnM3CnZlcnNpb25uczEwCnBhcmVudEdVSURuczgKcGFyZW50SURzNwpUVl9TaG93czEwCm1lZGlhX3R5cGVzNDQKY29tLmdpdGh1Yi5uZWFyYXRhLmppa2FucGxleDovLzExMDYxP2xhbmc9ZW5zNApndWlkczUKMTEwNjFzMgppZHIwCg__
2021-02-18 04:06:27,299 (1550acd6b640) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-02-18 04:06:27,301 (1550acd6b640) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.github.nearata.jikanplex/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNAoxOTI1czQKZGJpZGkwCnM3CnZlcnNpb25uczEwCnBhcmVudEdVSURuczgKcGFyZW50SURzNwpUVl9TaG93czEwCm1lZGlhX3R5cGVzNDQKY29tLmdpdGh1Yi5uZWFyYXRhLmppa2FucGxleDovLzExMDYxP2xhbmc9ZW5zNApndWlkczUKMTEwNjFzMgppZHIwCg__
2021-02-18 04:06:27,302 (1550acd6b640) :  DEBUG (model:32) - Loading model with GUID com.github.nearata.jikanplex://11061?lang=en
2021-02-18 04:06:27,304 (1550acd6b640) :  DEBUG (model:234) - Deserializing from /config/Plex Media Server/Metadata/TV Shows/c/600569dce7f0e2d4deabf9c47a20f3ca4f34ed5.bundle/Contents/com.github.nearata.jikanplex/Info.xml
2021-02-18 04:06:27,779 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/1925/tree'
2021-02-18 04:06:32,179 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/11061'
2021-02-18 04:06:38,390 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/11061/pictures'
2021-02-18 04:06:44,565 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/11061/characters_staff'
2021-02-18 04:06:50,825 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/11061/episodes/1'
2021-02-18 04:06:57,010 (1550acd6b640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/11061/episodes/2'
2021-02-18 04:07:02,420 (1550acd6b640) :  DEBUG (model:229) - Serializing to /config/Plex Media Server/Metadata/TV Shows/c/600569dce7f0e2d4deabf9c47a20f3ca4f34ed5.bundle/Contents/com.github.nearata.jikanplex/Info.xml
2021-02-18 04:07:02,432 (1550acd6b640) :  DEBUG (runtime:88) - Sending packed state data (109 bytes)
2021-02-18 04:07:02,433 (1550acd6b640) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by Nearata** [comment]
> 
> 
> ```shell
> posters_data = get_json(JIKAN_URL + JIKAN_ANIME_EPISODES.format(id=sequel_id))
> 
> KeyError: 'page'
> ```

i encountered this error with a multi season show. Also, the code is a lot dirty so `posters_data` refers to season episodes.

**Comment by Denrage** [comment]
> > ```shell
> > posters_data = get_json(JIKAN_URL + JIKAN_ANIME_EPISODES.format(id=sequel_id))
> > 
> > KeyError: 'page'
> > ```
> 
> i encountered this error with a multi season show. Also, the code is a lot dirty so `posters_data` refers to season episodes.

That information helped a lot and i can reproduce it now
```
2021-02-18 06:16:36,993 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/2075/tree'
2021-02-18 06:16:41,306 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/search/anime?q=Overlord&limit=10'
2021-02-18 06:16:44,444 (148b72e0f640) :  DEBUG (runtime:88) - Sending packed state data (109 bytes)
2021-02-18 06:16:44,445 (148b72e0f640) :  DEBUG (runtime:924) - Response: [200] str, 3744 bytes
2021-02-18 06:16:44,515 (148b72e0f640) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.github.nearata.jikanplex/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNAoyMDc1czQKZGJpZGkwCnM3CnZlcnNpb25uczEwCnBhcmVudEdVSURuczgKcGFyZW50SURzNwpUVl9TaG93czEwCm1lZGlhX3R5cGVzNDQKY29tLmdpdGh1Yi5uZWFyYXRhLmppa2FucGxleDovLzI5ODAzP2xhbmc9ZW5zNApndWlkczUKMjk4MDNzMgppZHIwCg__
2021-02-18 06:16:44,516 (148b72e0f640) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2021-02-18 06:16:44,517 (148b72e0f640) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.github.nearata.jikanplex/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNAoyMDc1czQKZGJpZGkwCnM3CnZlcnNpb25uczEwCnBhcmVudEdVSURuczgKcGFyZW50SURzNwpUVl9TaG93czEwCm1lZGlhX3R5cGVzNDQKY29tLmdpdGh1Yi5uZWFyYXRhLmppa2FucGxleDovLzI5ODAzP2xhbmc9ZW5zNApndWlkczUKMjk4MDNzMgppZHIwCg__
2021-02-18 06:16:44,518 (148b72e0f640) :  DEBUG (model:32) - Loading model with GUID com.github.nearata.jikanplex://29803?lang=en
2021-02-18 06:16:44,540 (148b72e0f640) :  DEBUG (model:234) - Deserializing from /config/Plex Media Server/Metadata/TV Shows/f/fbccbab98292b64c093b23368353416e5c569eb.bundle/Contents/com.github.nearata.jikanplex/Info.xml
2021-02-18 06:16:45,041 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/2075/tree'
2021-02-18 06:16:49,193 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/29803'
2021-02-18 06:16:55,400 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/29803/pictures'
2021-02-18 06:17:01,587 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/29803/characters_staff'
2021-02-18 06:17:07,793 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/29803/episodes/1'
2021-02-18 06:17:13,972 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/35073'
2021-02-18 06:17:20,157 (148b72e0f640) :  DEBUG (networking:143) - Requesting 'https://api.jikan.moe/v3/anime/35073/pictures'
2021-02-18 06:17:22,331 (148b72e0f640) :  CRITICAL (agentkit:1095) - Exception in the update function of agent named 'JikanPlex', called with guid 'com.github.nearata.jikanplex://29803?lang=en' (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-3945797bd/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1093, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/config/Plex Media Server/Plug-ins/JikanPlex.bundle/Contents/Code/__init__.py", line 188, in update
    posters_data = get_json(JIKAN_URL + JIKAN_ANIME_EPISODES.format(id=sequel_id))
KeyError: 'page'

2021-02-18 06:17:22,827 (148b72e0f640) :  DEBUG (model:229) - Serializing to /config/Plex Media Server/Metadata/TV Shows/f/fbccbab98292b64c093b23368353416e5c569eb.bundle/Contents/com.github.nearata.jikanplex/Info.xml
2021-02-18 06:17:22,834 (148b72e0f640) :  DEBUG (runtime:88) - Sending packed state data (109 bytes)
2021-02-18 06:17:22,834 (148b72e0f640) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

i'm going to fix it, thanks

**Comment by Nearata** [comment]
tested it for a bit, all good. thank you!

**Pull request merged**
